### ISSUE TITLE
Fifa Code: ENG

### ISSUE THREAD

**Issue by adamrama** [oxguy3/flags#1]
In Google Sheets I'm having a problem for fifa codes for teams that are not in fact countries but have their flag and fifa code.
For example: England (ENG), Wales (WAL), Nothern Ireland (NIR), etc...

**Comment by oxguy3** [comment]
I added rows at the bottom of the [Country codes and aliases](https://docs.google.com/spreadsheets/d/1GoDDhtoDuKwDv9pB5hKFkcHzhI420z2lr4szovryXaU/edit#gid=0) spreadsheet to support this use case.
