### ISSUE TITLE
Clean up NL flags folder

### ISSUE THREAD

**Issue by rlenders** [oxguy3/flags#5]
The Netherlands has [12 provinces](https://en.wikipedia.org/wiki/Provinces_of_the_Netherlands). Right now the [`nl`](https://github.com/oxguy3/flags/tree/gh-pages/svg/nl) folder contains 16 flags.

[`bq1.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/nl/bq1.svg), [`bq2.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/nl/bq2.svg) and [`bq3.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/nl/bq3.svg) can be removed, as they can already be found in the [`bq`](https://github.com/oxguy3/flags/tree/gh-pages/svg/bq) folder, which is a better location.

[`aw.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/nl/aw.svg), [`cw.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/nl/cw.svg) and [`sx.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/nl/sx.svg) are not flags from provinces of the Netherlands. I am not sure where these belong, but not here.

This leaves us with 10 flags, these are correct. [South Holland (zh)](https://en.wikipedia.org/wiki/South_Holland) and [Zeeland (ze)](https://en.wikipedia.org/wiki/Zeeland) are missing. These 2 should be added.

**Comment by oxguy3** [comment]
The goal here is to fully support the ISO 3166-2 standard, which sometimes has redundant codes. I don't want to force anyone using this repository to use one format or the other, so I'll have duplicate flags if the standard calls for it. All those flags are named according to the ISO-3166-2:NL; more info here: <https://en.wikipedia.org/wiki/ISO_3166-2:NL>

**Comment by rlenders** [comment]
I see. Still, ZH and ZE are missing. Could you add those?

**Comment by oxguy3** [comment]
Yep, just added them!

**Comment by rlenders** [comment]
Thanks for the quick responses!
