### ISSUE TITLE
Unofficial UK country code?

### ISSUE THREAD

**Issue by rlenders** [oxguy3/flags#7]
I noticed this repository contains [`uk.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/uk.svg), which is an unofficial country code as it's supposed to be GB. [`gb.svg`](https://github.com/oxguy3/flags/blob/gh-pages/svg/gb.svg) is here too, it is identical to UK.

Shouldn't the SVG flag image of UK just be removed?

**Comment by rlenders** [comment]
UK wouldn't be out of place anymore if #9 gets merged. When that happens this issue can be closed. If the pull request does not gets merged, I'd say UK should be removed.

**Comment by oxguy3** [comment]
I'd rather be as permissive as possible, so I've merged #9 and will be keeping the UK flag in place. Thanks for all your contributions!
